//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 11:42:28 AM CEST 
//


package rs.skupstinans.propis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NazivUvodnogDela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NazivUvodnogDela">
 *   &lt;restriction base="{http://www.skupstinans.rs/elementi}Naziv">
 *     &lt;enumeration value="Uvodne odredbe"/>
 *     &lt;enumeration value="Osnovne odredbe"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NazivUvodnogDela")
@XmlEnum
public enum NazivUvodnogDela {

    @XmlEnumValue("Uvodne odredbe")
    UVODNE_ODREDBE("Uvodne odredbe"),
    @XmlEnumValue("Osnovne odredbe")
    OSNOVNE_ODREDBE("Osnovne odredbe");
    private final String value;

    NazivUvodnogDela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NazivUvodnogDela fromValue(String v) {
        for (NazivUvodnogDela c: NazivUvodnogDela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
