//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 10:06:18 PM CEST 
//


package rs.skupstinans.amandman;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.skupstinans.rs/amandman}TipIzmene"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Obrazlozenje"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.skupstinans.rs/elementi}references use="required""/>
 *       &lt;attribute ref="{http://www.skupstinans.rs/elementi}id use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElementRefs({
        @XmlElementRef(name = "Izmena", namespace = "http://www.skupstinans.rs/amandman", type = Izmena.class),
        @XmlElementRef(name = "Dopuna", namespace = "http://www.skupstinans.rs/amandman", type = Dopuna.class),
        @XmlElementRef(name = "Brisanje", namespace = "http://www.skupstinans.rs/amandman", type = Brisanje.class),
        @XmlElementRef(name = "Obrazlozenje", namespace = "http://www.skupstinans.rs/elementi", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "references", namespace = "http://www.skupstinans.rs/elementi", required = true)
    protected String references;
    @XmlAttribute(name = "id", namespace = "http://www.skupstinans.rs/elementi", required = true)
    protected String id;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dopuna }
     * {@link String }
     * {@link Brisanje }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Izmena }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferences(String value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
