//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 03:17:14 PM CEST 
//


package rs.skupstinans.amandman;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import rs.skupstinans.elementi.Clan;
import rs.skupstinans.elementi.Deo;
import rs.skupstinans.elementi.Glava;
import rs.skupstinans.elementi.Odeljak;
import rs.skupstinans.elementi.Pododeljak;
import rs.skupstinans.elementi.Stav;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Deo"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Glava"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Odeljak"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Pododeljak"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Clan"/>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Stav"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deo",
    "glava",
    "odeljak",
    "pododeljak",
    "clan",
    "stav"
})
@XmlRootElement(name = "Dopuna")
public class Dopuna {

    @XmlElement(name = "Deo", namespace = "http://www.skupstinans.rs/elementi")
    protected Deo deo;
    @XmlElement(name = "Glava", namespace = "http://www.skupstinans.rs/elementi")
    protected Glava glava;
    @XmlElement(name = "Odeljak", namespace = "http://www.skupstinans.rs/elementi")
    protected Odeljak odeljak;
    @XmlElement(name = "Pododeljak", namespace = "http://www.skupstinans.rs/elementi")
    protected Pododeljak pododeljak;
    @XmlElement(name = "Clan", namespace = "http://www.skupstinans.rs/elementi")
    protected Clan clan;
    @XmlElement(name = "Stav", namespace = "http://www.skupstinans.rs/elementi")
    protected Stav stav;

    /**
     * Gets the value of the deo property.
     * 
     * @return
     *     possible object is
     *     {@link Deo }
     *     
     */
    public Deo getDeo() {
        return deo;
    }

    /**
     * Sets the value of the deo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deo }
     *     
     */
    public void setDeo(Deo value) {
        this.deo = value;
    }

    /**
     * Gets the value of the glava property.
     * 
     * @return
     *     possible object is
     *     {@link Glava }
     *     
     */
    public Glava getGlava() {
        return glava;
    }

    /**
     * Sets the value of the glava property.
     * 
     * @param value
     *     allowed object is
     *     {@link Glava }
     *     
     */
    public void setGlava(Glava value) {
        this.glava = value;
    }

    /**
     * Gets the value of the odeljak property.
     * 
     * @return
     *     possible object is
     *     {@link Odeljak }
     *     
     */
    public Odeljak getOdeljak() {
        return odeljak;
    }

    /**
     * Sets the value of the odeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odeljak }
     *     
     */
    public void setOdeljak(Odeljak value) {
        this.odeljak = value;
    }

    /**
     * Gets the value of the pododeljak property.
     * 
     * @return
     *     possible object is
     *     {@link Pododeljak }
     *     
     */
    public Pododeljak getPododeljak() {
        return pododeljak;
    }

    /**
     * Sets the value of the pododeljak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pododeljak }
     *     
     */
    public void setPododeljak(Pododeljak value) {
        this.pododeljak = value;
    }

    /**
     * Gets the value of the clan property.
     * 
     * @return
     *     possible object is
     *     {@link Clan }
     *     
     */
    public Clan getClan() {
        return clan;
    }

    /**
     * Sets the value of the clan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clan }
     *     
     */
    public void setClan(Clan value) {
        this.clan = value;
    }

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link Stav }
     *     
     */
    public Stav getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stav }
     *     
     */
    public void setStav(Stav value) {
        this.stav = value;
    }

}
