//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 03:22:51 PM CEST 
//


package rs.skupstinans.amandman;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.skupstinans.amandman package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.skupstinans.amandman
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izmena }
     * 
     */
    public Izmena createIzmena() {
        return new Izmena();
    }

    /**
     * Create an instance of {@link Brisanje }
     * 
     */
    public Brisanje createBrisanje() {
        return new Brisanje();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Dopuna }
     * 
     */
    public Dopuna createDopuna() {
        return new Dopuna();
    }

    /**
     * Create an instance of {@link Amandmani }
     * 
     */
    public Amandmani createAmandmani() {
        return new Amandmani();
    }

}
