//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 10:06:18 PM CEST 
//


package rs.skupstinans.elementi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.skupstinans.rs/elementi}Naziv"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.skupstinans.rs/elementi}Pododeljak" maxOccurs="unbounded" minOccurs="2"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.skupstinans.rs/elementi}Clan" maxOccurs="unbounded"/>
 *             &lt;element ref="{http://www.skupstinans.rs/elementi}Pododeljak" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.skupstinans.rs/elementi}id use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Odeljak")
public class Odeljak {

    @XmlElementRefs({
        @XmlElementRef(name = "Pododeljak", namespace = "http://www.skupstinans.rs/elementi", type = Pododeljak.class, required = false),
        @XmlElementRef(name = "Clan", namespace = "http://www.skupstinans.rs/elementi", type = Clan.class, required = false),
        @XmlElementRef(name = "Naziv", namespace = "http://www.skupstinans.rs/elementi", type = JAXBElement.class, required = false)
    })
    protected List<Object> content;
    @XmlAttribute(name = "id", namespace = "http://www.skupstinans.rs/elementi", required = true)
    protected String id;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Pododeljak" is used by two different parts of a schema. See: 
     * line 37 of file:/C:/EclipseWorkspace/XMLProject/data/XML/Elementi.xsd
     * line 34 of file:/C:/EclipseWorkspace/XMLProject/data/XML/Elementi.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pododeljak }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Clan }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
